import os
import json
import re
from openai import AsyncOpenAI

class Supervisor:
    def __init__(self, sandbox, worker_agent=None, model_name: str = "gemma2:27b", max_retries=3):
        self.sandbox = sandbox
        self.worker = worker_agent
        self.model_name = model_name
        self.max_retries = max_retries
        self.client = AsyncOpenAI(base_url="http://localhost:11434/v1", api_key="local")

    async def execute_with_oversight(self, task_id: str, task_description: str, file_path: str, initial_code: str) -> bool:
        current_code = initial_code
        attempt = 1
        
        # Determine the absolute path for file writing
        full_file_path = os.path.join(self.sandbox.workspace_path, file_path)

        while attempt <= self.max_retries:
            print(f"[Supervisor] AI evaluating '{task_id}' - Attempt {attempt}/{self.max_retries}")
            
            # 1. Write the code to the workspace (still useful for manual review or future sandbox runs)
            os.makedirs(os.path.dirname(full_file_path), exist_ok=True)
            with open(full_file_path, "w", encoding="utf-8") as f:
                f.write(current_code)

            # 2. AI Code Review Prompt
            sys_prompt = (
                "You are a strict, expert Lead Software Engineer. Your job is to review code generated by a junior developer.\n"
                "Compare the provided CODE against the provided TASK DESCRIPTION.\n"
                "Check for completeness, logical errors, missing imports, and syntax issues.\n"
                "You MUST respond ONLY with a JSON object in this exact format:\n"
                '{"passed": true, "feedback": "Code perfectly meets requirements."}\n'
                "or\n"
                '{"passed": false, "feedback": "Detailed explanation of what is wrong and exactly how to fix it."}'
            )
            
            user_prompt = f"TASK DESCRIPTION:\n{task_description}\n\nCODE GENERATED:\n{current_code}"

            # 3. Call the LLM to judge the code
            try:
                response = await self.client.chat.completions.create(
                    model=self.model_name, # Updated to use gemma2:27b
                    messages=[
                        {"role": "system", "content": sys_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    temperature=0.1,
                    extra_body={
                        "options": {
                            "num_ctx": 8192
                        }
                    }
                )
                
                # 4. Parse the JSON verdict safely
                raw_output = response.choices[0].message.content
                json_match = re.search(r'\{.*?\}', raw_output, re.DOTALL)
                
                if json_match:
                    verdict = json.loads(json_match.group(0))
                else:
                    raise ValueError("No JSON object found in model response.")
                    
            except Exception as e:
                print(f"[Supervisor] Error parsing AI review: {e}")
                # If the supervisor fails to parse, force a retry by failing the evaluation
                verdict = {"passed": False, "feedback": f"System error during review parsing. Please review your code syntax."}

            # 5. Evaluate the verdict
            if verdict.get("passed") is True:
                print(f"[Supervisor] Task '{task_id}' passed AI review! Code is clean.")
                return True

            # 6. Handle Failure: Pass the AI's feedback directly into the worker's fix_code method
            feedback = verdict.get("feedback", "No specific feedback provided.")
            print(f"[Supervisor] Task '{task_id}' failed AI review.\nFeedback: {feedback}\nBouncing back to Worker.")
            
            # Feed the detailed critique back to the worker
            current_code = await self.worker.fix_code(
                original_task=task_description,
                broken_code=current_code,
                error_log=f"AI Supervisor Code Review Feedback:\n{feedback}"
            )
            
            attempt += 1

        print(f"[Supervisor] Task '{task_id}' failed after {self.max_retries} attempts.")
        return False